In [63]:
# Import

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [64]:
df = pd.read_csv(r"C:\Users\delbi\Desktop\Jithin ICT Data\Exit Test\train.csv")
df

,player_id,name,age,gender,country,height,weight,ball_controlling_skills,body_reflexes,body_balance,...,strong_foot,behaviour_rating,matches_played,fitness_rating,trophies_won,dedication_level,coaching,years_of_experience,no_of_disqualifications,selection
0,PLID_4964,Keva Horan,23,M,Ukraine,6'2,176lbs,77.0,58.0,47.0,...,Right,7.7,NaN,8.1,2.0,High,Talent Hunt,8.0,0.0,1
1,PLID_11234,Herma Tann,18,M,Russia,5'10,148lbs,54.0,69.0,70.0,...,Any,5.3,0.0,NaN,3.0,Medium,Source,3.0,0.0,0
2,PLID_19127,Eilene Kizer,16,F,Spain,6'2,172lbs,34.0,43.0,45.0,...,Left,4.7,0.0,6.6,5.0,Low,Academy,2.0,0.0,1
3,PLID_17467,Andrea Badgett,27,M,Chile,5'11,165lbs,79.0,73.0,76.0,...,Right,8.6,113.0,8.6,6.0,Medium,Academy,13.0,16.0,1
4,PLID_9661,Jeremiah Bumbalough,19,F,Argentina,5'8,158lbs,47.0,61.0,74.0,...,Right,NaN,0.0,5.7,5.0,Medium,Academy,4.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13989,PLID_10956,Viva Stepney,20,M,Uruguay,6'0,161lbs,60.0,48.0,62.0,...,Right,6.0,NaN,7.6,2.0,Medium,Academy,6.0,0.0,1
13990,PLID_17290,Illa Pitre,18,F,England,5'10,165lbs,53.0,68.0,59.0,...,Right,5.3,0.0,5.6,3.0,Medium,Academy,4.0,0.0,0
13991,PLID_5193,Marylouise Mosley,17,M,Japan,6'0,172lbs,56.0,73.0,62.0,...,Left,5.7,0.0,7.7,3.0,Low,Talent Hunt,2.0,0.0,1
13992,PLID_12173,Teri Escamilla,20,F,Ukraine,5'10,150lbs,71.0,69.0,70.0,...,Left,6.8,1.0,5.8,4.0,Medium,Academy,6.0,0.0,1
13993,PLID_236,Darius Schuman,16,F,Chile,5'8,159lbs,53.0,59.0,67.0,...,Right,4.2,0.0,6.7,0.0,Medium,Source,1.0,0.0,0

In [65]:
# unique values

unique_values = {col: df[col].nunique() for col in df.columns}
for col, counts in unique_values.items():
    print(f" {col}: {counts}")

 player_id: 13994
 name: 13994
 age: 39
 gender: 2
 country: 163
 height: 31
 weight: 88
 ball_controlling_skills: 89
 body_reflexes: 84
 body_balance: 86
 jumping_skills: 74
 penalties_conversion_rate: 86
 mental_strength: 83
 goalkeeping_skills: 65
 defending_skills: 78
 passing_skills: 77
 dribbling_skills: 48
 shot_accuracy: 79
 body_strength_stamina: 73
 max_running_speed: 166
 strong_foot: 4
 behaviour_rating: 64
 matches_played: 18
 fitness_rating: 85
 trophies_won: 10
 dedication_level: 3
 coaching: 4
 years_of_experience: 25
 no_of_disqualifications: 17
 selection: 2

In [66]:

df=df.drop(['player_id','name','country'], axis=1)

In [67]:
# check for missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13994 entries, 0 to 13993
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        13994 non-null  int64
 1   gender                     13975 non-null  object
 2   height                     13994 non-null  object
 3   weight                     13577 non-null  object
 4   ball_controlling_skills    13581 non-null  float64
 5   body_reflexes              13994 non-null  float64
 6   body_balance               13994 non-null  float64
 7   jumping_skills             13970 non-null  float64
 8   penalties_conversion_rate  13964 non-null  float64
 9   mental_strength            13966 non-null  float64
 10  goalkeeping_skills         13994 non-null  float64
 11  defending_skills           13994 non-null  float64
 12  passing_skills             13994 non-null  float64
 13  dribbling_skills           13994 non-null  float64
 14  shot_accuracy              13422 non-null  float64
 15  body_strength_stamina      13994 non-null  float64
 16  max_running_speed          13994 non-null  float64
 17  strong_foot                13442 non-null  object
 18  behaviour_rating           13291 non-null  float64
 19  matches_played             13328 non-null  float64
 20  fitness_rating             13299 non-null  float64
 21  trophies_won               13994 non-null  float64
 22  dedication_level           13994 non-null  object
 23  coaching                   13869 non-null  object
 24  years_of_experience        13850 non-null  float64
 25  no_of_disqualifications    13994 non-null  float64
 26  selection                  13994 non-null  int64
dtypes: float64(19), int64(2), object(6)
memory usage: 2.9+ MB

In [68]:
# Remove the unit "lbs" from the data

df['weight'] =df['weight'].str.replace('lbs', '')

In [69]:
# Convert height into inches

def convert_height(hgt):
    feet, inches = hgt.split("'")
    total_inches = int(feet) * 12 + int(inches.replace('"', ''))
    return total_inches

df['height'] =df['height'].apply(convert_height)

In [70]:
# convert weight to Float type
df['weight'] = pd.to_numeric(df['weight'], errors='coerce').astype('Float64')

In [71]:
df.columns

Index(['age', 'gender', 'height', 'weight', 'ball_controlling_skills',
       'body_reflexes', 'body_balance', 'jumping_skills',
       'penalties_conversion_rate', 'mental_strength', 'goalkeeping_skills',
       'defending_skills', 'passing_skills', 'dribbling_skills',
       'shot_accuracy', 'body_strength_stamina', 'max_running_speed',
       'strong_foot', 'behaviour_rating', 'matches_played', 'fitness_rating',
       'trophies_won', 'dedication_level', 'coaching', 'years_of_experience',
       'no_of_disqualifications', 'selection'],
      dtype='object')

In [72]:
num = ['age', 'height', 'weight', 'ball_controlling_skills',
       'body_reflexes', 'body_balance', 'jumping_skills',
       'penalties_conversion_rate', 'mental_strength', 'goalkeeping_skills',
       'defending_skills', 'passing_skills', 'dribbling_skills',
       'shot_accuracy', 'body_strength_stamina', 'max_running_speed',
       'behaviour_rating', 'matches_played', 'fitness_rating',
       'trophies_won', 'years_of_experience',
       'no_of_disqualifications']
cat = ['gender','strong_foot','coaching','dedication_level']

In [73]:
# use median to fill missing values of numerical values

for i in num:
    df[i]=df[i].fillna(df[i].median())

In [74]:
# use mode to fill missing values of categorical columns

for i in cat:
    df[i]=df[i].fillna(df[i].mode()[0])

In [75]:
# check for missing values
# all columns must be filled now.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13994 entries, 0 to 13993
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        13994 non-null  int64
 1   gender                     13994 non-null  object
 2   height                     13994 non-null  int64
 3   weight                     13994 non-null  Float64
 4   ball_controlling_skills    13994 non-null  float64
 5   body_reflexes              13994 non-null  float64
 6   body_balance               13994 non-null  float64
 7   jumping_skills             13994 non-null  float64
 8   penalties_conversion_rate  13994 non-null  float64
 9   mental_strength            13994 non-null  float64
 10  goalkeeping_skills         13994 non-null  float64
 11  defending_skills           13994 non-null  float64
 12  passing_skills             13994 non-null  float64
 13  dribbling_skills           13994 non-null  float64
 14  shot_accuracy              13994 non-null  float64
 15  body_strength_stamina      13994 non-null  float64
 16  max_running_speed          13994 non-null  float64
 17  strong_foot                13994 non-null  object
 18  behaviour_rating           13994 non-null  float64
 19  matches_played             13994 non-null  float64
 20  fitness_rating             13994 non-null  float64
 21  trophies_won               13994 non-null  float64
 22  dedication_level           13994 non-null  object
 23  coaching                   13994 non-null  object
 24  years_of_experience        13994 non-null  float64
 25  no_of_disqualifications    13994 non-null  float64
 26  selection                  13994 non-null  int64
dtypes: Float64(1), float64(19), int64(3), object(4)
memory usage: 2.9+ MB

In [76]:
# encode the categorical variables

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [77]:
# Label encoder for ordinal variable dedication level

le=LabelEncoder()
df['dedication_level']=le.fit_transform(df['dedication_level'])

In [78]:
categ = ['gender', 'strong_foot', 'coaching']
ohe = OneHotEncoder()

for i in categ:
    transformed_data = ohe.fit_transform(df[i].values.reshape(-1, 1))
    df_transformed = pd.DataFrame(transformed_data.toarray(), columns=ohe.get_feature_names_out([i]))
    df = pd.concat([df, df_transformed], axis=1)


df.drop(categ, axis=1, inplace=True)

In [79]:
df

,age,height,weight,ball_controlling_skills,body_reflexes,body_balance,jumping_skills,penalties_conversion_rate,mental_strength,goalkeeping_skills,...,gender_F,gender_M,strong_foot_Any,strong_foot_Left,strong_foot_None,strong_foot_Right,coaching_Academy,coaching_Source,coaching_Talent Hunt,coaching_Unknown
0,23,74,176.0,77.0,58.0,47.0,59.0,41.0,73.0,13.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,18,70,148.0,54.0,69.0,70.0,62.0,53.0,43.0,10.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,16,74,172.0,34.0,43.0,45.0,69.0,49.0,45.0,10.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,27,71,165.0,79.0,73.0,76.0,86.0,81.0,80.0,3.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,19,68,158.0,47.0,61.0,74.0,57.0,49.0,35.0,9.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13989,20,72,161.0,60.0,48.0,62.0,60.0,40.0,61.0,10.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
13990,18,70,165.0,53.0,68.0,59.0,73.0,24.0,55.0,11.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
13991,17,72,172.0,56.0,73.0,62.0,50.0,47.0,64.0,10.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
13992,20,70,150.0,71.0,69.0,70.0,51.0,56.0,59.0,9.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
13993,16,68,159.0,53.0,59.0,67.0,54.0,62.0,54.0,6.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

In [80]:
from sklearn.preprocessing import MinMaxScaler

In [81]:
scaler = MinMaxScaler()
for i in num:
    numb=np.array(df[i])
    numb=numb.reshape(-1, 1)
    df[i] = scaler.fit_transform(numb)

In [82]:
X = df.iloc[:,0:len(df)-1]
y=df['selection']

In [83]:
# Split data into training and testing sets

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [84]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Initialize the KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=3) 

# Train the model
knn_classifier.fit(X_train, y_train)

# Predict on the test set
y_pred = knn_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0